// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSelection() {
  return window['go']['main']['App']['ClearSelection']();
}

export function ExportToCSV(arg1) {
  return window['go']['main']['App']['ExportToCSV'](arg1);
}

export function GetConnectionCount() {
  return window['go']['main']['App']['GetConnectionCount']();
}

export function GetConnectionStats(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetConnectionStats'](arg1, arg2, arg3, arg4);
}

export function GetConnections(arg1) {
  return window['go']['main']['App']['GetConnections'](arg1);
}

export function GetHealthThresholds() {
  return window['go']['main']['App']['GetHealthThresholds']();
}

export function GetUpdateInterval() {
  return window['go']['main']['App']['GetUpdateInterval']();
}

export function IsAdministrator() {
  return window['go']['main']['App']['IsAdministrator']();
}

export function SetHealthThresholds(arg1) {
  return window['go']['main']['App']['SetHealthThresholds'](arg1);
}

export function SetRTTThreshold(arg1) {
  return window['go']['main']['App']['SetRTTThreshold'](arg1);
}

export function SetRetransmissionThreshold(arg1) {
  return window['go']['main']['App']['SetRetransmissionThreshold'](arg1);
}

export function SetUpdateInterval(arg1) {
  return window['go']['main']['App']['SetUpdateInterval'](arg1);
}
