// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tcpmonitor} from '../models';

export function ClearSelection():Promise<void>;

export function ExportToCSV(arg1:string):Promise<void>;

export function GetConnectionCount():Promise<number>;

export function GetConnectionStats(arg1:string,arg2:number,arg3:string,arg4:number):Promise<tcpmonitor.ExtendedStats>;

export function GetConnections(arg1:tcpmonitor.FilterOptions):Promise<Array<tcpmonitor.ConnectionInfo>>;

export function GetHealthThresholds():Promise<tcpmonitor.HealthThresholds>;

export function GetUpdateInterval():Promise<number>;

export function IsAdministrator():Promise<boolean>;

export function SetHealthThresholds(arg1:tcpmonitor.HealthThresholds):Promise<void>;

export function SetRTTThreshold(arg1:number):Promise<void>;

export function SetRetransmissionThreshold(arg1:number):Promise<void>;

export function SetUpdateInterval(arg1:number):Promise<void>;
